/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ProblemasCidadeRouteImport } from './routes/problemas-cidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedMeusProblemasRouteImport } from './routes/_authenticated/meus-problemas'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPrefeituraRouteImport } from './routes/_authenticated/prefeitura'
import { Route as AuthenticatedRegistrarRouteImport } from './routes/_authenticated/registrar'
import { Route as ProblemaIdRouteImport } from './routes/problema.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemasCidadeRoute = ProblemasCidadeRouteImport.update({
  id: '/problemas-cidade',
  path: '/problemas-cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeusProblemasRoute =
  AuthenticatedMeusProblemasRouteImport.update({
    id: '/meus-problemas',
    path: '/meus-problemas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrefeituraRoute = AuthenticatedPrefeituraRouteImport.update({
  id: '/prefeitura',
  path: '/prefeitura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrarRoute = AuthenticatedRegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ProblemaIdRoute = ProblemaIdRouteImport.update({
  id: '/problema/$id',
  path: '/problema/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/problemas-cidade': typeof ProblemasCidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-problemas': typeof AuthenticatedMeusProblemasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/prefeitura': typeof AuthenticatedPrefeituraRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/problema/$id': typeof ProblemaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/problemas-cidade': typeof ProblemasCidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/meus-problemas': typeof AuthenticatedMeusProblemasRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/prefeitura': typeof AuthenticatedPrefeituraRoute
  '/registrar': typeof AuthenticatedRegistrarRoute
  '/problema/$id': typeof ProblemaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/problemas-cidade': typeof ProblemasCidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/meus-problemas': typeof AuthenticatedMeusProblemasRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/prefeitura': typeof AuthenticatedPrefeituraRoute
  '/_authenticated/registrar': typeof AuthenticatedRegistrarRoute
  '/problema/$id': typeof ProblemaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/problemas-cidade'
    | '/redefinir-senha'
    | '/sobre'
    | '/admin'
    | '/dashboard'
    | '/meus-problemas'
    | '/notificacoes'
    | '/perfil'
    | '/prefeitura'
    | '/registrar'
    | '/problema/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/problemas-cidade'
    | '/redefinir-senha'
    | '/sobre'
    | '/admin'
    | '/dashboard'
    | '/meus-problemas'
    | '/notificacoes'
    | '/perfil'
    | '/prefeitura'
    | '/registrar'
    | '/problema/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/problemas-cidade'
    | '/redefinir-senha'
    | '/sobre'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/meus-problemas'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/prefeitura'
    | '/_authenticated/registrar'
    | '/problema/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProblemasCidadeRoute: typeof ProblemasCidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreRoute: typeof SobreRoute
  ProblemaIdRoute: typeof ProblemaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problemas-cidade': {
      id: '/problemas-cidade'
      path: '/problemas-cidade'
      fullPath: '/problemas-cidade'
      preLoaderRoute: typeof ProblemasCidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meus-problemas': {
      id: '/_authenticated/meus-problemas'
      path: '/meus-problemas'
      fullPath: '/meus-problemas'
      preLoaderRoute: typeof AuthenticatedMeusProblemasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prefeitura': {
      id: '/_authenticated/prefeitura'
      path: '/prefeitura'
      fullPath: '/prefeitura'
      preLoaderRoute: typeof AuthenticatedPrefeituraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrar': {
      id: '/_authenticated/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof AuthenticatedRegistrarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/problema/$id': {
      id: '/problema/$id'
      path: '/problema/$id'
      fullPath: '/problema/$id'
      preLoaderRoute: typeof ProblemaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMeusProblemasRoute: typeof AuthenticatedMeusProblemasRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPrefeituraRoute: typeof AuthenticatedPrefeituraRoute
  AuthenticatedRegistrarRoute: typeof AuthenticatedRegistrarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMeusProblemasRoute: AuthenticatedMeusProblemasRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPrefeituraRoute: AuthenticatedPrefeituraRoute,
  AuthenticatedRegistrarRoute: AuthenticatedRegistrarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProblemasCidadeRoute: ProblemasCidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreRoute: SobreRoute,
  ProblemaIdRoute: ProblemaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
